### PR TITLE
Migrating to pyproject.toml

### PR DESCRIPTION
**Pull request by cerrussell**
#102 

I have created and populated a pyproject.toml file. Existing configuration files have been preserved, though I did see fit to comment out the metadata in setup.py to ensure the generated installation is getting that information from the intended source. Similarly, workflows have been updated to reference the toml rather than setup.py or requirements files - e.g. installing dependencies using the dev option I created in project.optional-dependencies.

The new justbuild.yml served only to allow me to verify the generated build within GA since I obviously couldn't publish from my fork. Probably should just remove that before merging but preserved in case inspection of the generated dists are desired (uploaded as an artifact).

### CODE REVIEW

**Comment by prabhu** [comment]
@cerrussell shall we remove setup.py instead of commenting out all lines? Would there be any issues with removing the file or leaving it unmodified?

**Comment by cerrussell** [comment]
@prabhu I don't see an issue with either of those options for this project. I will note that the tool.setuptools table within pyproject.toml is still beta. The significance of that here is that we have to specify the packages to include under tool.setuptools due to the project layout. Otherwise the setuptools backend attempts to auto-discover packages - which is another beta feature and did not work correctly when I tried it. 

So basically using pyproject.toml depends on beta functionality and that gives me pause despite having no issues even when I remove the setup.py file.

**Comment by cerrussell** [comment]
@prabhu I removed setup.py. I'm happy to take a look at the vulnerability repo.

**Comment by prabhu** [comment]
Thank you so much!

**Pull request merged**
