### PR TITLE
Feature/courtesy readme enhancements

### PR DESCRIPTION
**Pull request by bon-accord**

### CODE REVIEW

**Comment by prabhu** [comment]
Thanks for the PR! Can you rebase since some information on python local is missing in your version.

**Comment by bon-accord** [comment]
How is that now?

**Comment by prabhu** [comment]
Some more work is required. Let me take the changes manually. Thanks for the help mate!

**Comment by bon-accord** [comment]
Managed to rebase my fork with your upstream properly on the second
attempt.

I can't push to branches on your repo directly so used a fork.

Just making a few suggestions, nothing of any real value :-)

**Pull request closed without merging**
